- name: breaking
  color: ffcc00
  description: Breaking change.
- name: bug
  color: d73a4a
  description: Something isn't working
- name: dependencies
  color: 0366d6
  description: Pull requests that update a dependency file
- name: github_actions
  color: "000000"
  description: Update of github actions
- name: documentation
  color: 1bc4a5
  description: Improvements or additions to documentation
- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: help wanted
  color: "008672"
  description: Extra attention is needed
- name: invalid
  color: e4e669
  description: This doesn't seem right
- name: nochangelog
  color: "555555"
  description: Exclude pull requests from changelog
- name: question
  color: d876e3
  description: Further information is requested
- name: removed
  color: e99695
  description: Removed piece of functionalities.
- name: tests
  color: bfd4f2
  description: CI, CD and testing related changes
- name: wontfix
  color: ffffff
  description: This will not be worked on
- name: discussion
  color: c2e0c6
  description: Some discussion around the project
- name: hacktoberfest
  color: ffa663
  description: Good issues for Hacktoberfest
- name: answered
  color: 0ee2b6
  description: Automatically closes as answered after a delay
- name: waiting
  color: 5f7972
  description: Automatically closes if no answer after a delay
- name: fund
  color: 0E8A16
  description: Add a section linking to polar.sh for funding the issue.
