# See https://pre-commit.com/
# See https://black.readthedocs.io/en/stable/integrations/source_version_control.html
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
