name: Sync Github labels

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: 3.x
      - name: Install labels
        run: pip install labels
      - name: Sync config with Github
        run: labels -u ${{ github.repository_owner }} -t ${{ secrets.GITHUB_TOKEN }} sync -f .github/labels.toml
